;//
;// knob_parser_tree.asm         generated by wordtree.cpp
;//                    from sourcefile .\source\OBJECTS\Controls\knob_parser\knob_parser.asm
;//

NODE_:

    xor eax, eax
    lodsb
    xlat
.DATA
BYTETABLE_ LABEL BYTE
    db 0,21,21,21,21,1,2,21
    db 3,21,21,21,21,21,21,21
    db 21,21,21,21,21,21,21,21
    db 21,21,21,21,4,5,6,7
    db 21,8,9,10,21,21,11,12
    db 13,14,21,15,21,16,17,18
    db 19,20
ALIGN 4
JUMPTABLE_ LABEL DWORD
    dd NODE_1_PERCENT    ;//0 37
    dd NODE_1_STAR    ;//1 42
    dd NODE_1_PLUS    ;//2 43
    dd NODE_1_MINUS    ;//3 45
    dd NODE_1A    ;//4 65
    dd NODE_1B    ;//5 66
    dd NODE_1C    ;//6 67
    dd NODE_1D    ;//7 68
    dd NODE_1F    ;//8 70
    dd NODE_1G    ;//9 71
    dd NODE_1H    ;//10 72
    dd NODE_1K    ;//11 75
    dd NODE_1L    ;//12 76
    dd NODE_1M    ;//13 77
    dd NODE_1N    ;//14 78
    dd NODE_1P    ;//15 80
    dd NODE_1R    ;//16 82
    dd NODE_1S    ;//17 83
    dd NODE_1T    ;//18 84
    dd NODE_1U    ;//19 85
    dd NODE_1V    ;//20 86
    dd return_fail;//21
.CODE
    xor edx, edx
    sub al, 37
    jb  return_fail
    cmp al, 49
    ja  return_fail
    mov dl, BYTETABLE_[eax]
    jmp JUMPTABLE_[edx*4]

NODE_1V:

    lodsb
    xlat
    cmp al, 'A'
    jne return_fail

NODE_1V2A:

    lodsb
    xlat
    cmp al, 'L'
    jne return_fail

NODE_1V2A3L:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_VAL
    cmp al, '9'
    ja  @F
    cmp al, '0'
    jae NODE_VAL
    cmp al, '-'
    je  NODE_VAL
    cmp al, '+'
    je  NODE_VAL
    cmp al, '.'
    je  NODE_VAL
 @@:
    cmp al, 'U'
    jne return_fail

NODE_1V2A3L4U:

    lodsb
    xlat
    cmp al, 'E'
    jne return_fail

NODE_1V2A3L4U5E:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_VALUE
    jmp return_fail

NODE_1U:

    lodsb
    xlat
    cmp al, 'S'
    jne return_fail

NODE_1U2S:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_US
    jmp return_fail

NODE_1T:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_T
    cmp al, 'E'
    je  NODE_1T2E
    cmp al, 'R'
    je  NODE_1T2R
    cmp al, 'U'
    jne return_fail

NODE_1T2U:

    lodsb
    xlat
    cmp al, 'R'
    jne return_fail

NODE_1T2U3R:

    lodsb
    xlat
    cmp al, 'N'
    jne return_fail

NODE_1T2U3R4N:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_TURN
    cmp al, 'S'
    jne return_fail

NODE_1T2U3R4N5S:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_TURNS
    jmp return_fail

NODE_1T2R:

    lodsb
    xlat
    cmp al, 'U'
    jne return_fail

NODE_1T2R3U:

    lodsb
    xlat
    cmp al, 'E'
    jne return_fail

NODE_1T2R3U4E:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_TRUE
    jmp return_fail

NODE_1T2E:

    lodsb
    xlat
    cmp al, 'M'
    jne return_fail

NODE_1T2E3M:

    lodsb
    xlat
    cmp al, 'P'
    jne return_fail

NODE_1T2E3M4P:

    lodsb
    xlat
    cmp al, 'O'
    jne return_fail

NODE_1T2E3M4P5O:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_TEMPO
    jmp return_fail

NODE_1S:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_S
    cmp al, 'A'
    je  NODE_1S2A
    cmp al, 'E'
    jne return_fail

NODE_1S2E:

    lodsb
    xlat
    cmp al, 'C'
    jne return_fail

NODE_1S2E3C:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_SEC
    cmp al, 'O'
    jne return_fail

NODE_1S2E3C4O:

    lodsb
    xlat
    cmp al, 'N'
    jne return_fail

NODE_1S2E3C4O5N:

    lodsb
    xlat
    cmp al, 'D'
    jne return_fail

NODE_1S2E3C4O5N6D:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_SECOND
    cmp al, 'S'
    jne return_fail

NODE_1S2E3C4O5N6D7S:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_SECONDS
    jmp return_fail

NODE_1S2A:

    lodsb
    xlat
    cmp al, 'M'
    jne return_fail

NODE_1S2A3M:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_SAM
    cmp al, '9'
    ja  @F
    cmp al, '0'
    jae NODE_SAM
    cmp al, '-'
    je  NODE_SAM
    cmp al, '+'
    je  NODE_SAM
    cmp al, '.'
    je  NODE_SAM
 @@:
    cmp al, 'P'
    jne return_fail

NODE_1S2A3M4P:

    lodsb
    xlat
    cmp al, 'L'
    jne return_fail

NODE_1S2A3M4P5L:

    lodsb
    xlat
    cmp al, 'E'
    jne return_fail

NODE_1S2A3M4P5L6E:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_SAMPLE
    cmp al, 'S'
    jne return_fail

NODE_1S2A3M4P5L6E7S:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_SAMPLES
    jmp return_fail

NODE_1R:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_R
    cmp al, '9'
    ja  @F
    cmp al, '0'
    jae NODE_R
    cmp al, '-'
    je  NODE_R
    cmp al, '+'
    je  NODE_R
    cmp al, '.'
    je  NODE_R
 @@:
    cmp al, 'I'
    jne return_fail

NODE_1R2I:

    lodsb
    xlat
    cmp al, 'G'
    jne return_fail

NODE_1R2I3G:

    lodsb
    xlat
    cmp al, 'H'
    jne return_fail

NODE_1R2I3G4H:

    lodsb
    xlat
    cmp al, 'T'
    jne return_fail

NODE_1R2I3G4H5T:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_RIGHT
    jmp return_fail

NODE_1P:

    lodsb
    xlat
    cmp al, 'A'
    je  NODE_1P2A
    cmp al, 'E'
    je  NODE_1P2E
    cmp al, 'H'
    jne return_fail

NODE_1P2H:

    lodsb
    xlat
    cmp al, 'A'
    jne return_fail

NODE_1P2H3A:

    lodsb
    xlat
    cmp al, 'S'
    jne return_fail

NODE_1P2H3A4S:

    lodsb
    xlat
    cmp al, 'E'
    jne return_fail

NODE_1P2H3A4S5E:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_PHASE
    jmp return_fail

NODE_1P2E:

    lodsb
    xlat
    cmp al, 'R'
    jne return_fail

NODE_1P2E3R:

    lodsb
    xlat
    cmp al, 'C'
    jne return_fail

NODE_1P2E3R4C:

    lodsb
    xlat
    cmp al, 'E'
    jne return_fail

NODE_1P2E3R4C5E:

    lodsb
    xlat
    cmp al, 'N'
    jne return_fail

NODE_1P2E3R4C5E6N:

    lodsb
    xlat
    cmp al, 'T'
    jne return_fail

NODE_1P2E3R4C5E6N7T:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_PERCENT
    jmp return_fail

NODE_1P2A:

    lodsb
    xlat
    cmp al, 'N'
    jne return_fail

NODE_1P2A3N:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_PAN
    cmp al, '9'
    ja  @F
    cmp al, '0'
    jae NODE_PAN
    cmp al, '-'
    je  NODE_PAN
    cmp al, '+'
    je  NODE_PAN
    cmp al, '.'
    je  NODE_PAN
 @@:
    cmp al, 'N'
    jne return_fail

NODE_1P2A3N4N:

    lodsb
    xlat
    cmp al, 'E'
    jne return_fail

NODE_1P2A3N4N5E:

    lodsb
    xlat
    cmp al, 'R'
    jne return_fail

NODE_1P2A3N4N5E6R:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_PANNER
    jmp return_fail

NODE_1N:

    lodsb
    xlat
    cmp al, 'E'
    jb  return_fail
    je  NODE_1N2E
    cmp al, 'H'
    je  NODE_1N2H
    cmp al, 'O'
    je  NODE_1N2O
    cmp al, 'S'
    jne return_fail

NODE_1N2S:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_NS
    jmp return_fail

NODE_1N2O:

    lodsb
    xlat
    cmp al, 'T'
    jne return_fail

NODE_1N2O3T:

    lodsb
    xlat
    cmp al, 'E'
    jne return_fail

NODE_1N2O3T4E:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_NOTE
    jmp return_fail

NODE_1N2H:

    lodsb
    xlat
    cmp al, 'Z'
    jne return_fail

NODE_1N2H3Z:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_NHZ
    jmp return_fail

NODE_1N2E:

    lodsb
    xlat
    cmp al, 'G'
    jne return_fail

NODE_1N2E3G:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_NEG
    jmp return_fail

NODE_1M:

    lodsb
    xlat
    cmp al, 'H'
    jb  return_fail
    je  NODE_1M2H
    cmp al, 'I'
    je  NODE_1M2I
    cmp al, 'S'
    je  NODE_1M2S
    cmp al, 'U'
    jne return_fail

NODE_1M2U:

    lodsb
    xlat
    cmp al, 'L'
    jne return_fail

NODE_1M2U3L:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_MUL
    cmp al, 'T'
    jne return_fail

NODE_1M2U3L4T:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_MULT
    cmp al, 'I'
    jne return_fail

NODE_1M2U3L4T5I:

    lodsb
    xlat
    cmp al, 'P'
    jne return_fail

NODE_1M2U3L4T5I6P:

    lodsb
    xlat
    cmp al, 'L'
    jne return_fail

NODE_1M2U3L4T5I6P7L:

    lodsb
    xlat
    cmp al, 'Y'
    jne return_fail

NODE_1M2U3L4T5I6P7L8Y:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_MULTIPLY
    jmp return_fail

NODE_1M2S:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_MS
    jmp return_fail

NODE_1M2I:

    lodsb
    xlat
    cmp al, 'D'
    jne return_fail

NODE_1M2I3D:

    lodsb
    xlat
    cmp al, 'I'
    jne return_fail

NODE_1M2I3D4I:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_MIDI
    cmp al, '9'
    ja  return_fail
    cmp al, '0'
    jae NODE_MIDI
    cmp al, '-'
    je  NODE_MIDI
    cmp al, '+'
    je  NODE_MIDI
    cmp al, '.'
    je  NODE_MIDI
    jmp return_fail

NODE_1M2H:

    lodsb
    xlat
    cmp al, 'Z'
    jne return_fail

NODE_1M2H3Z:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_MHZ
    jmp return_fail

NODE_1L:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_L
    cmp al, '9'
    ja  @F
    cmp al, '0'
    jae NODE_L
    cmp al, '-'
    je  NODE_L
    cmp al, '+'
    je  NODE_L
    cmp al, '.'
    je  NODE_L
 @@:
    cmp al, 'E'
    je  NODE_1L2E
    cmp al, 'I'
    je  NODE_1L2I
    cmp al, 'O'
    jne return_fail

NODE_1L2O:

    lodsb
    xlat
    cmp al, 'G'
    jne return_fail

NODE_1L2O3G:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_LOG
    cmp al, 'I'
    jne return_fail

NODE_1L2O3G4I:

    lodsb
    xlat
    cmp al, 'C'
    jne return_fail

NODE_1L2O3G4I5C:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_LOGIC
    jmp return_fail

NODE_1L2I:

    lodsb
    xlat
    cmp al, 'N'
    jne return_fail

NODE_1L2I3N:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_LIN
    cmp al, 'E'
    jne return_fail

NODE_1L2I3N4E:

    lodsb
    xlat
    cmp al, 'A'
    jne return_fail

NODE_1L2I3N4E5A:

    lodsb
    xlat
    cmp al, 'R'
    jne return_fail

NODE_1L2I3N4E5A6R:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_LINEAR
    jmp return_fail

NODE_1L2E:

    lodsb
    xlat
    cmp al, 'F'
    jne return_fail

NODE_1L2E3F:

    lodsb
    xlat
    cmp al, 'T'
    jne return_fail

NODE_1L2E3F4T:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_LEFT
    jmp return_fail

NODE_1K:

    lodsb
    xlat
    cmp al, 'H'
    je  NODE_1K2H
    cmp al, 'N'
    je  NODE_1K2N
    cmp al, 'S'
    jne return_fail

NODE_1K2S:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_KS
    jmp return_fail

NODE_1K2N:

    lodsb
    xlat
    cmp al, 'O'
    jne return_fail

NODE_1K2N3O:

    lodsb
    xlat
    cmp al, 'B'
    jne return_fail

NODE_1K2N3O4B:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_KNOB
    jmp return_fail

NODE_1K2H:

    lodsb
    xlat
    cmp al, 'Z'
    jne return_fail

NODE_1K2H3Z:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_KHZ
    jmp return_fail

NODE_1H:

    lodsb
    xlat
    cmp al, 'E'
    je  NODE_1H2E
    cmp al, 'Z'
    jne return_fail

NODE_1H2Z:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_HZ
    jmp return_fail

NODE_1H2E:

    lodsb
    xlat
    cmp al, 'R'
    jne return_fail

NODE_1H2E3R:

    lodsb
    xlat
    cmp al, 'T'
    jne return_fail

NODE_1H2E3R4T:

    lodsb
    xlat
    cmp al, 'Z'
    jne return_fail

NODE_1H2E3R4T5Z:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_HERTZ
    jmp return_fail

NODE_1G:

    lodsb
    xlat
    cmp al, 'H'
    jne return_fail

NODE_1G2H:

    lodsb
    xlat
    cmp al, 'Z'
    jne return_fail

NODE_1G2H3Z:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_GHZ
    jmp return_fail

NODE_1F:

    lodsb
    xlat
    cmp al, 'A'
    jne return_fail

NODE_1F2A:

    lodsb
    xlat
    cmp al, 'L'
    jne return_fail

NODE_1F2A3L:

    lodsb
    xlat
    cmp al, 'S'
    jne return_fail

NODE_1F2A3L4S:

    lodsb
    xlat
    cmp al, 'E'
    jne return_fail

NODE_1F2A3L4S5E:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_FALSE
    jmp return_fail

NODE_1D:

    lodsb
    xlat
    cmp al, 'B'
    je  NODE_1D2B
    cmp al, 'E'
    jne return_fail

NODE_1D2E:

    lodsb
    xlat
    cmp al, 'C'
    je  NODE_1D2E3C
    cmp al, 'G'
    jne return_fail

NODE_1D2E3G:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_DEG
    cmp al, 'R'
    jne return_fail

NODE_1D2E3G4R:

    lodsb
    xlat
    cmp al, 'E'
    jne return_fail

NODE_1D2E3G4R5E:

    lodsb
    xlat
    cmp al, 'E'
    jne return_fail

NODE_1D2E3G4R5E6E:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_DEGREE
    cmp al, 'S'
    jne return_fail

NODE_1D2E3G4R5E6E7S:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_DEGREES
    jmp return_fail

NODE_1D2E3C:

    lodsb
    xlat
    cmp al, 'I'
    jne return_fail

NODE_1D2E3C4I:

    lodsb
    xlat
    cmp al, 'B'
    jne return_fail

NODE_1D2E3C4I5B:

    lodsb
    xlat
    cmp al, 'E'
    jne return_fail

NODE_1D2E3C4I5B6E:

    lodsb
    xlat
    cmp al, 'L'
    jne return_fail

NODE_1D2E3C4I5B6E7L:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_DECIBEL
    cmp al, 'S'
    jne return_fail

NODE_1D2E3C4I5B6E7L8S:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_DECIBELS
    jmp return_fail

NODE_1D2B:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_DB
    jmp return_fail

NODE_1C:

    lodsb
    xlat
    cmp al, 'E'
    jne return_fail

NODE_1C2E:

    lodsb
    xlat
    cmp al, 'N'
    jne return_fail

NODE_1C2E3N:

    lodsb
    xlat
    cmp al, 'T'
    jne return_fail

NODE_1C2E3N4T:

    lodsb
    xlat
    cmp al, 'E'
    jne return_fail

NODE_1C2E3N4T5E:

    lodsb
    xlat
    cmp al, 'R'
    jne return_fail

NODE_1C2E3N4T5E6R:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_CENTER
    jmp return_fail

NODE_1B:

    lodsb
    xlat
    cmp al, 'I'
    je  NODE_1B2I
    cmp al, 'O'
    je  NODE_1B2O
    cmp al, 'P'
    jne return_fail

NODE_1B2P:

    lodsb
    xlat
    cmp al, 'M'
    jne return_fail

NODE_1B2P3M:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_BPM
    jmp return_fail

NODE_1B2O:

    lodsb
    xlat
    cmp al, 'O'
    jne return_fail

NODE_1B2O3O:

    lodsb
    xlat
    cmp al, 'L'
    jne return_fail

NODE_1B2O3O4L:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_BOOL
    jmp return_fail

NODE_1B2I:

    lodsb
    xlat
    cmp al, 'N'
    jne return_fail

NODE_1B2I3N:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_BIN
    cmp al, '9'
    ja  @F
    cmp al, '0'
    jae NODE_BIN
    cmp al, '-'
    je  NODE_BIN
    cmp al, '+'
    je  NODE_BIN
    cmp al, '.'
    je  NODE_BIN
 @@:
    cmp al, 'S'
    jne return_fail

NODE_1B2I3N4S:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_BINS
    jmp return_fail

NODE_1A:

    lodsb
    xlat
    cmp al, 'D'
    je  NODE_1A2D
    cmp al, 'N'
    je  NODE_1A2N
    cmp al, 'U'
    jne return_fail

NODE_1A2U:

    lodsb
    xlat
    cmp al, 'D'
    je  NODE_1A2U3D
    cmp al, 'T'
    jne return_fail

NODE_1A2U3T:

    lodsb
    xlat
    cmp al, 'O'
    jne return_fail

NODE_1A2U3T4O:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_AUTO
    jmp return_fail

NODE_1A2U3D:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_AUD
    cmp al, 'I'
    jne return_fail

NODE_1A2U3D4I:

    lodsb
    xlat
    cmp al, 'O'
    jne return_fail

NODE_1A2U3D4I5O:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_AUDIO
    jmp return_fail

NODE_1A2N:

    lodsb
    xlat
    cmp al, 'G'
    jne return_fail

NODE_1A2N3G:

    lodsb
    xlat
    cmp al, 'L'
    jne return_fail

NODE_1A2N3G4L:

    lodsb
    xlat
    cmp al, 'E'
    jne return_fail

NODE_1A2N3G4L5E:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_ANGLE
    jmp return_fail

NODE_1A2D:

    lodsb
    xlat
    cmp al, 'D'
    jne return_fail

NODE_1A2D3D:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE_ADD
    jmp return_fail

NODE_1_MINUS:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE__MINUS
    jmp return_fail

NODE_1_PLUS:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE__PLUS
    jmp return_fail

NODE_1_STAR:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE__STAR
    jmp return_fail

NODE_1_PERCENT:

    lodsb
    xlat
    cmp al, ' '
    jbe NODE__PERCENT
    jmp return_fail

