;//
;// C:\WINDOWS\Desktop\ABox200\VR\noise\noise.asm       generated by GBUILD.cpp
;//
noise_container_points LABEL fPOINT
        fPOINT {1.718400e+001,2.858497e+000}
        fPOINT {1.626407e+001,-2.347499e+000}
        fPOINT {1.739023e+001,-1.332791e+000}
        fPOINT {1.632728e+001,-3.566202e-001}
        fPOINT {1.770537e+001,7.294566e-001}
        fPOINT {1.391761e+001,1.869823e+000}

noise_container_dwFlags equ SHAPE_IS_CONTAINER OR SHAPE_RGN_OFS_OC OR SHAPE_IS_POLYGON OR 6 OR SHAPE_BUILD_OUT1 OR SHAPE_BUILD_OUT2 OR SHAPE_BUILD_OUT3
noise_container GDI_CONTAINER {0,0.000000e+000,{1.200000e+001,1.200000e+001},
,,,,{ noise_container_dwFlags,
{OFFSET noise_container_points},{1.650000e+001,1.690000e+001},next_noise_container}}


