;//
;// C:\WINDOWS\Desktop\VR\noise\noise_m.asm     generated by GBUILD.cpp
;//
_dwFlags equ SHAPE_IS_CONTAINER OR SHAPE_RGN_OFS_OC
 GDI_CONTAINER {0,1.000000e-001,{1.600000e+001,1.600000e+001},
,,,,{ _dwFlags,
{},{-1.812500e+001,-5.750000e+000},next_}}


