;//
;// C:\WINDOWS\Desktop\ABox200\VR\iir\iir.asm       generated by GBUILD.cpp
;//
iir_container_dwFlags equ SHAPE_IS_CONTAINER OR SHAPE_RGN_OFS_OC OR SHAPE_IS_CIRCLE OR SHAPE_BUILD_OUT1 OR SHAPE_BUILD_OUT2 OR SHAPE_BUILD_OUT3
iir_container GDI_CONTAINER {0,0.000000e+000,{4.560702e+001,4.560702e+001},
,,,,{ iir_container_dwFlags,
{},{4.560702e+001,4.560702e+001},next_iir_container}}


