;//
;// C:\WINDOWS\Desktop\ABox200\VR\button\button.asm     generated by GBUILD.cpp
;//
button_container_points LABEL fPOINT
        fPOINT {1.960229e+001,-2.482787e+000}
        fPOINT {1.986692e+001,-6.485346e-001}
        fPOINT {1.937496e+001,6.142495e-001}
        fPOINT {1.910352e+001,2.517286e+000}

button_container_dwFlags equ SHAPE_IS_CONTAINER OR SHAPE_RGN_OFS_OC OR SHAPE_IS_POLYGON OR 4 OR SHAPE_BUILD_OUT1 OR SHAPE_BUILD_OUT2 OR SHAPE_BUILD_OUT3
button_container GDI_CONTAINER {3,8.000000e-002,{1.400000e+001,1.000000e+001},
,,,,{ button_container_dwFlags,
{OFFSET button_container_points},{1.550000e+001,1.200000e+001},next_button_container}}


