;//
;// C:\WINDOWS\Desktop\ABox200\VR\display_palette.asm       generated by GBUILD.cpp
;//
display_palette_points LABEL fPOINT
        fPOINT {3.452535e+001,-1.745468e+000}
        fPOINT {3.452535e+001,-1.396124e+000}
        fPOINT {3.452535e+001,1.396124e+000}
        fPOINT {3.452535e+001,1.745468e+000}

display_palette_dwFlags equ SHAPE_IS_CONTAINER OR SHAPE_RGN_OFS_OC OR SHAPE_IS_POLYGON OR 4
display_palette GDI_CONTAINER {0,1.000000e-001,{1.600000e+001,1.600000e+001},
,,,,{ display_palette_dwFlags,
{OFFSET display_palette_points},{6.000000e+000,3.400000e+001},next_display_palette}}


