;//
;// C:\WINDOWS\Desktop\ABox200\VR\slider\slider_h.asm       generated by GBUILD.cpp
;//
slider_container_h_points LABEL fPOINT
        fPOINT {6.921208e+001,-2.974663e+000}
        fPOINT {6.995177e+001,-1.651487e-001}
        fPOINT {6.995177e+001,1.651487e-001}
        fPOINT {6.921208e+001,2.974663e+000}

slider_container_h_dwFlags equ SHAPE_IS_CONTAINER OR SHAPE_RGN_OFS_OC OR SHAPE_IS_POLYGON OR 4 OR SHAPE_BUILD_OUT1 OR SHAPE_BUILD_OUT2 OR SHAPE_BUILD_OUT3
slider_container_h GDI_CONTAINER {3,1.000000e-001,{7.400000e+001,1.100000e+001},
,,,,{ slider_container_h_dwFlags,
{OFFSET slider_container_h_points},{6.825000e+001,1.150000e+001},next_slider_container_h}}


