;//
;// C:\WINDOWS\Desktop\ABox200\VR\slider\slider_v.asm       generated by GBUILD.cpp
;//
slider_container_v_points LABEL fPOINT
        fPOINT {6.960446e+001,-1.739579e+000}
        fPOINT {6.960446e+001,-1.402014e+000}
        fPOINT {6.930116e+001,1.401268e+000}
        fPOINT {6.930116e+001,1.740324e+000}

slider_container_v_dwFlags equ SHAPE_IS_CONTAINER OR SHAPE_RGN_OFS_OC OR SHAPE_IS_POLYGON OR 4 OR SHAPE_BUILD_OUT1 OR SHAPE_BUILD_OUT2 OR SHAPE_BUILD_OUT3
slider_container_v GDI_CONTAINER {3,1.000000e-001,{1.100000e+001,7.400000e+001},
,,,,{ slider_container_v_dwFlags,
{OFFSET slider_container_v_points},{1.169231e+001,6.861539e+001},next_slider_container_v}}


