;//
;// C:\WINDOWS\Desktop\ABox200\VR\t_rite\mplex.asm      generated by GBUILD.cpp
;//
mplex_container_points LABEL fPOINT
        fPOINT {1.456709e+001,-2.365903e+000}
        fPOINT {1.462395e+001,-2.191046e+000}
        fPOINT {1.397855e+001,-3.353244e-001}
        fPOINT {1.471224e+001,-4.079368e-002}
        fPOINT {1.423692e+001,2.483858e-001}
        fPOINT {1.231666e+001,2.088935e+000}
        fPOINT {1.332066e+001,2.292451e+000}
        fPOINT {1.312098e+001,2.485897e+000}

mplex_container_dwFlags equ SHAPE_IS_CONTAINER OR SHAPE_RGN_OFS_OC OR SHAPE_IS_POLYGON OR 8 OR SHAPE_BUILD_OUT1 OR SHAPE_BUILD_OUT2 OR SHAPE_BUILD_OUT3
mplex_container GDI_CONTAINER {2,-1.700000e-001,{1.200000e+001,8.000000e+000},
,,,,{ mplex_container_dwFlags,
{OFFSET mplex_container_points},{1.040000e+001,1.190000e+001},next_mplex_container}}


