;//
;// C:\WINDOWS\Desktop\ABox200\VR\knob\knob.asm     generated by GBUILD.cpp
;//
knob_container_points LABEL fPOINT
        fPOINT {3.466256e+001,-2.270411e+000}
        fPOINT {3.435543e+001,-8.818719e-001}
        fPOINT {3.398628e+001,8.728935e-001}
        fPOINT {3.429670e+001,2.279423e+000}

knob_container_dwFlags equ SHAPE_IS_CONTAINER OR SHAPE_RGN_OFS_OC OR SHAPE_IS_POLYGON OR 4 OR SHAPE_BUILD_OUT1 OR SHAPE_BUILD_OUT2 OR SHAPE_BUILD_OUT3
knob_container GDI_CONTAINER {3,7.000000e-002,{2.200000e+001,2.600000e+001},
,,,,{ knob_container_dwFlags,
{OFFSET knob_container_points},{2.232000e+001,2.652000e+001},next_knob_container}}


