;//
;// C:\WINDOWS\Desktop\ABox200\VR\circle\circle.asm     generated by GBUILD.cpp
;//
circle_container_dwFlags equ SHAPE_IS_CONTAINER OR SHAPE_RGN_OFS_OC OR SHAPE_IS_CIRCLE OR SHAPE_BUILD_OUT1 OR SHAPE_BUILD_OUT2 OR SHAPE_BUILD_OUT3
circle_container GDI_CONTAINER {0,0.000000e+000,{1.240000e+001,1.240000e+001},
,,,,{ circle_container_dwFlags,
{},{1.240000e+001,1.240000e+001},next_circle_container}}


