;//
;// C:\WINDOWS\Desktop\circle\math.asm      generated by GBUILD.cpp
;//
math_container_dwFlags equ SHAPE_IS_CONTAINER OR SHAPE_RGN_OFS_OC OR SHAPE_IS_CIRCLE OR SHAPE_BUILD_OUT1 OR SHAPE_BUILD_OUT2 OR SHAPE_BUILD_OUT3
math_container GDI_CONTAINER {0,0.000000e+000,{1.587549e+001,1.587549e+001},
,,,,{ math_container_dwFlags,
{},{1.587549e+001,1.587549e+001},next_math_container}}


