;//
;// C:\WINDOWS\Desktop\ABox200\VR\mixer\mixer.asm       generated by GBUILD.cpp
;//
mixer_container_points LABEL fPOINT
        fPOINT {6.318404e+001,-1.735078e+000}
        fPOINT {4.342299e+001,-1.346299e+000}
        fPOINT {4.244867e+001,1.341055e+000}
        fPOINT {6.219772e+001,1.737707e+000}

mixer_container_dwFlags equ SHAPE_IS_CONTAINER OR SHAPE_RGN_OFS_OC OR SHAPE_IS_POLYGON OR 4 OR SHAPE_BUILD_OUT1 OR SHAPE_BUILD_OUT2 OR SHAPE_BUILD_OUT3
mixer_container GDI_CONTAINER {3,1.000000e-001,{8.000000e+000,4.800000e+001},
,,,,{ mixer_container_dwFlags,
{OFFSET mixer_container_points},{1.033333e+001,6.233334e+001},next_mixer_container}}


