;//
;// C:\WINDOWS\Desktop\ABox200\VR\t_left\dplex.asm      generated by GBUILD.cpp
;//
dplex_container_points LABEL fPOINT
        fPOINT {1.503729e+001,-2.899840e+000}
        fPOINT {1.412409e+001,-9.513699e-001}
        fPOINT {1.521611e+001,-7.435622e-001}
        fPOINT {1.388092e+001,6.319742e-001}
        fPOINT {1.362351e+001,8.685394e-001}
        fPOINT {1.242578e+001,9.917220e-001}
        fPOINT {1.482768e+001,2.930970e+000}

dplex_container_dwFlags equ SHAPE_IS_CONTAINER OR SHAPE_RGN_OFS_OC OR SHAPE_IS_POLYGON OR 7 OR SHAPE_BUILD_OUT1 OR SHAPE_BUILD_OUT2 OR SHAPE_BUILD_OUT3
dplex_container GDI_CONTAINER {2,1.700000e-001,{1.200000e+001,8.000000e+000},
,,,,{ dplex_container_dwFlags,
{OFFSET dplex_container_points},{1.460000e+001,1.150000e+001},next_dplex_container}}


