;//
;// C:\WINDOWS\Desktop\ABox200\VR\prism\fftop.asm       generated by GBUILD.cpp
;//
fftop_container_points LABEL fPOINT
        fPOINT {2.266120e+001,-2.541351e+000}
        fPOINT {2.307553e+001,-5.880026e-001}
        fPOINT {2.258871e+001,5.548452e-001}
        fPOINT {2.216529e+001,2.574863e+000}

fftop_container_dwFlags equ SHAPE_IS_CONTAINER OR SHAPE_RGN_OFS_OC OR SHAPE_IS_POLYGON OR 4 OR SHAPE_BUILD_OUT1 OR SHAPE_BUILD_OUT2 OR SHAPE_BUILD_OUT3
fftop_container GDI_CONTAINER {3,1.000000e-001,{1.900000e+001,1.200000e+001},
,,,,{ fftop_container_dwFlags,
{OFFSET fftop_container_points},{1.870000e+001,1.280000e+001},next_fftop_container}}


