;//
;// C:\WINDOWS\Desktop\ABox200\VR\prism\prism.asm       generated by GBUILD.cpp
;//
prism_container_points LABEL fPOINT
        fPOINT {2.236382e+001,-2.344337e+000}
        fPOINT {2.218988e+001,-8.053159e-001}
        fPOINT {2.156748e+001,7.772017e-001}
        fPOINT {2.174641e+001,2.372453e+000}

prism_container_dwFlags equ SHAPE_IS_CONTAINER OR SHAPE_RGN_OFS_OC OR SHAPE_IS_POLYGON OR 4 OR SHAPE_BUILD_OUT1 OR SHAPE_BUILD_OUT2 OR SHAPE_BUILD_OUT3
prism_container GDI_CONTAINER {3,1.000000e-001,{1.600000e+001,1.600000e+001},
,,,,{ prism_container_dwFlags,
{OFFSET prism_container_points},{1.562500e+001,1.600000e+001},next_prism_container}}


