;//
;// C:\WINDOWS\Desktop\ABox200\VR\group\pinint.asm      generated by GBUILD.cpp
;//
pinint_container_points LABEL fPOINT
        fPOINT {1.913970e+001,-2.537287e+000}
        fPOINT {1.924269e+001,-6.006145e-001}
        fPOINT {1.952962e+001,6.217376e-001}
        fPOINT {1.942815e+001,2.516108e+000}

pinint_container_dwFlags equ SHAPE_IS_CONTAINER OR SHAPE_RGN_OFS_OC OR SHAPE_IS_POLYGON OR 4 OR SHAPE_BUILD_OUT1 OR SHAPE_BUILD_OUT2 OR SHAPE_BUILD_OUT3
pinint_container GDI_CONTAINER {3,1.000000e-001,{1.500000e+001,1.100000e+001},
,,,,{ pinint_container_dwFlags,
{OFFSET pinint_container_points},{1.575000e+001,1.087500e+001},next_pinint_container}}


