;//
;// C:\WINDOWS\Desktop\ABox200\VR\devices\devices.asm       generated by GBUILD.cpp
;//
devices_container_points LABEL fPOINT
        fPOINT {2.691665e+001,-2.452668e+000}
        fPOINT {2.846267e+001,-2.317540e+000}
        fPOINT {2.949158e+001,-2.157754e+000}
        fPOINT {2.922877e+001,-2.061648e+000}
        fPOINT {2.945199e+001,-1.058201e+000}
        fPOINT {2.964835e+001,-9.692810e-001}
        fPOINT {2.940668e+001,-8.683175e-001}
        fPOINT {2.564453e+001,-6.409014e-001}
        fPOINT {2.499605e+001,6.052635e-001}
        fPOINT {2.750578e+001,7.625450e-001}
        fPOINT {2.800022e+001,9.233270e-001}
        fPOINT {2.813745e+001,1.077122e+000}
        fPOINT {2.742915e+001,2.032632e+000}
        fPOINT {2.693408e+001,2.206872e+000}
        fPOINT {2.697438e+001,2.312490e+000}
        fPOINT {2.586670e+001,2.496373e+000}

devices_container_dwFlags equ SHAPE_IS_CONTAINER OR SHAPE_RGN_OFS_OC OR SHAPE_IS_POLYGON OR 16 OR SHAPE_BUILD_OUT1 OR SHAPE_BUILD_OUT2 OR SHAPE_BUILD_OUT3
devices_container GDI_CONTAINER {3,9.000000e-002,{1.600000e+001,2.000000e+001},
,,,,{ devices_container_dwFlags,
{OFFSET devices_container_points},{2.077778e+001,2.577778e+001},next_devices_container}}


