;//
;// C:\WINDOWS\Desktop\ABox200\VR\devices\devices_m.asm     generated by GBUILD.cpp
;//
_dwFlags equ SHAPE_IS_CONTAINER OR SHAPE_RGN_OFS_OC
 GDI_CONTAINER {0,1.000000e-001,{1.600000e+001,1.600000e+001},
,,,,{ _dwFlags,
{},{2.000000e+000,2.000000e+000},next_}}


