;//
;// C:\WINDOWS\Desktop\ABox200\VR\oval\FILTER\filter.asm        generated by GBUILD.cpp
;//
filter_container_dwFlags equ SHAPE_IS_CONTAINER OR SHAPE_RGN_OFS_OC OR SHAPE_IS_CIRCLE OR SHAPE_BUILD_OUT1 OR SHAPE_BUILD_OUT2 OR SHAPE_BUILD_OUT3
filter_container GDI_CONTAINER {0,0.000000e+000,{2.222222e+001,1.177778e+001},
,,,,{ filter_container_dwFlags,
{},{2.222222e+001,1.177778e+001},next_filter_container}}


