;//
;// C:\WINDOWS\Desktop\ABox200\VR\SH\sh.asm     generated by GBUILD.cpp
;//
sh_container_points LABEL fPOINT
        fPOINT {1.397151e+001,-2.158799e+000}
        fPOINT {1.603122e+001,-6.241881e-002}
        fPOINT {1.386768e+001,2.163799e+000}

sh_container_dwFlags equ SHAPE_IS_CONTAINER OR SHAPE_RGN_OFS_OC OR SHAPE_IS_POLYGON OR 3 OR SHAPE_BUILD_OUT1 OR SHAPE_BUILD_OUT2 OR SHAPE_BUILD_OUT3
sh_container GDI_CONTAINER {2,-1.800000e-001,{8.000000e+000,7.000000e+000},
,,,,{ sh_container_dwFlags,
{OFFSET sh_container_points},{7.750000e+000,1.162500e+001},next_sh_container}}


