;// This file is part of the Analog Box open source project.
;// Copyright 1999-2011 Andy J Turner
;//
;//     This program is free software: you can redistribute it and/or modify
;//     it under the terms of the GNU General Public License as published by
;//     the Free Software Foundation, either version 3 of the License, or
;//     (at your option) any later version.
;//
;//     This program is distributed in the hope that it will be useful,
;//     but WITHOUT ANY WARRANTY; without even the implied warranty of
;//     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;//     GNU General Public License for more details.
;//
;//     You should have received a copy of the GNU General Public License
;//     along with this program.  If not, see <http://www.gnu.org/licenses/>.
;//
;////////////////////////////////////////////////////////////////////////////
;//
;// Authors:    AJT Andy J Turner
;//
;// History:
;//
;//     2.41 Mar 04, 2011 AJT
;//         Initial port to GPLv3
;//
;//     ABOX242 AJT -- detabified
;//
;//##////////////////////////////////////////////////////////////////////////
;//
;// ABox_strings.inc
;//



    EXTERNDEF   sz_Left:BYTE
    EXTERNDEF   sz_Right:BYTE
    EXTERNDEF   sz_Amplitude:BYTE
    EXTERNDEF   sz_Delay:BYTE
    EXTERNDEF   sz_Decay:BYTE

    EXTERNDEF   sz_Write:BYTE
    EXTERNDEF   sz_SampleRate:BYTE
    EXTERNDEF   sz_Move:BYTE
    EXTERNDEF   sz_Seek:BYTE
    EXTERNDEF   sz_SeekPosition:BYTE
    EXTERNDEF   sz_CurrentPosition:BYTE
    EXTERNDEF   sz_FileSize:BYTE

    EXTERNDEF   sz_Data:BYTE
    EXTERNDEF   sz_Column:BYTE
    EXTERNDEF   sz_Row:BYTE
    EXTERNDEF   sz_NumColumn:BYTE
    EXTERNDEF   sz_NumRow:BYTE
    EXTERNDEF   sz_Erase:BYTE
    EXTERNDEF   sz_NextColumn:BYTE
    EXTERNDEF   sz_NextRow:BYTE
    EXTERNDEF   sz_ReRead:BYTE

    EXTERNDEF   sz_Frequency:BYTE
    EXTERNDEF   sz_Phase:BYTE
    EXTERNDEF   sz_Offset:BYTE
    EXTERNDEF   sz_Switch:BYTE

    EXTERNDEF   sz_Count:BYTE
    EXTERNDEF   sz_Reset:BYTE
    EXTERNDEF   sz_Resonance:BYTE

    EXTERNDEF   sz_Sample:BYTE
    EXTERNDEF   sz_Pan:BYTE

    EXTERNDEF   sz_Cascade:BYTE
    EXTERNDEF   sz_Time:BYTE

    EXTERNDEF   sz_Index:BYTE
    EXTERNDEF   sz_Spectrum:BYTE
    EXTERNDEF   sz_Shift:BYTE
    EXTERNDEF   sz_Scale:BYTE
    EXTERNDEF   sz_Real:BYTE
    EXTERNDEF   sz_Imag:BYTE

    EXTERNDEF   sz_Enable:BYTE

    EXTERNDEF   sz_SeedValue:BYTE
    EXTERNDEF   sz_Restart:BYTE
    EXTERNDEF   sz_NextValue:BYTE

    EXTERNDEF   sz_Range:BYTE
    EXTERNDEF   sz_Sweep:BYTE

    EXTERNDEF   sz_Step:BYTE
    EXTERNDEF   sz_StepSize:BYTE
    EXTERNDEF   sz_Damping:BYTE
    EXTERNDEF   sz_InitialValue:BYTE

    EXTERNDEF   sz_Parameter:BYTE

    EXTERNDEF   sz_Positive:BYTE
    EXTERNDEF   sz_Negative:BYTE
    EXTERNDEF   sz_Any:BYTE
    EXTERNDEF   sz_EdgeTrigger:BYTE
    EXTERNDEF   sz_Gate:BYTE

    EXTERNDEF   sz_Midi:BYTE
    EXTERNDEF   sz_Logic:BYTE
    EXTERNDEF   sz_Spectral:BYTE
    EXTERNDEF   sz_Input:BYTE
    EXTERNDEF   sz_Output:BYTE

    EXTERNDEF   sz_Stream:BYTE
    EXTERNDEF   sz_Number:BYTE
    EXTERNDEF   sz_Value:BYTE
    EXTERNDEF   sz_Event:BYTE


