;//
;// C:\WINDOWS\Desktop\ABox200\VR\qkey\qkey.asm     generated by GBUILD.cpp
;//
qkey_container_points LABEL fPOINT
        fPOINT {6.575961e+001,-2.975730e+000}
        fPOINT {6.406948e+001,-1.702806e-001}
        fPOINT {6.384292e+001,1.482261e-001}
        fPOINT {6.553890e+001,2.997230e+000}

qkey_container_dwFlags equ SHAPE_IS_CONTAINER OR SHAPE_RGN_OFS_OC OR SHAPE_IS_POLYGON OR 4 OR SHAPE_BUILD_OUT1 OR SHAPE_BUILD_OUT2 OR SHAPE_BUILD_OUT3
qkey_container GDI_CONTAINER {3,1.100000e-001,{7.000000e+001,1.300000e+001},
,,,,{ qkey_container_dwFlags,
{OFFSET qkey_container_points},{6.485715e+001,1.085714e+001},next_qkey_container}}


