;//
;// C:\WINDOWS\Desktop\ABox200\VR\r_rect\r_rect.asm     generated by GBUILD.cpp
;//
r_rect_container_points LABEL fPOINT
        fPOINT {1.592779e+001,-2.909304e+000}
        fPOINT {1.587648e+001,-2.684987e+000}
        fPOINT {1.518337e+001,-2.500287e+000}
        fPOINT {1.372144e+001,-2.270200e+000}
        fPOINT {1.361474e+001,-8.807602e-001}
        fPOINT {1.498379e+001,-6.512874e-001}
        fPOINT {1.599414e+001,-4.356829e-001}
        fPOINT {1.596720e+001,-1.943250e-001}
        fPOINT {1.583947e+001,1.478494e-001}
        fPOINT {1.594370e+001,3.134863e-001}
        fPOINT {1.494899e+001,5.385075e-001}
        fPOINT {1.391891e+001,8.277457e-001}
        fPOINT {1.314555e+001,2.257418e+000}
        fPOINT {1.460308e+001,2.477546e+000}
        fPOINT {1.531725e+001,2.673079e+000}
        fPOINT {1.591863e+001,2.935984e+000}

r_rect_container_dwFlags equ SHAPE_IS_CONTAINER OR SHAPE_RGN_OFS_OC OR SHAPE_IS_POLYGON OR 16 OR SHAPE_BUILD_OUT1 OR SHAPE_BUILD_OUT2 OR SHAPE_BUILD_OUT3
r_rect_container GDI_CONTAINER {3,5.000000e-002,{1.500000e+001,1.000000e+001},
,,,,{ r_rect_container_dwFlags,
{OFFSET r_rect_container_points},{1.558333e+001,1.050000e+001},next_r_rect_container}}


