;//     source\popup_strings.asm
;//     generated by build_popup200.cpp

;//
OPTION CASEMAP:NONE

.586
.MODEL FLAT

        .NOLIST
        include <abox.inc>
        .LIST

.DATA

    sz_ db 0
    sz_0 db '0',0
    sz_1 db '1',0
    sz_10 db '10',0
    sz_10_dot_8Hz_slash_ db '10.8Hz/',0
    sz_11 db '11',0
    sz_11_dot_0KHz db '11.0KHz',0
    sz_11_dot_6_space_ms_slash_ db '11.6 ms/',0
    sz_12 db '12',0
    sz_13 db '13',0
    sz_14 db '14',0
    sz_15 db '15',0
    sz_16 db '16',0
    sz_1C_amp_P_space__space__space__space_2_space_poles db '1C&P    2 poles',0
    sz_1C_amp_Z_space__space__space__space_2_space_zeros db '1C&Z    2 zeros',0
    sz_1_dot_48_space_sec db '1.48 sec',0
    sz_1_slash_256 db '1/256',0
    sz_2 db '2',0
    sz_21_dot_5Hz_slash_ db '21.5Hz/',0
    sz_22_dot_0_space_kHz db '22.0 kHz',0
    sz_23_dot_2_space_ms db '23.2 ms',0
    sz_23_dot_2_space_ms_slash_ db '23.2 ms/',0
    sz_23_dot_8_space_sec db '23.8 sec',0
    sz_2_amp__caret__lparen__space__rparen_ db '2&^( )',0
    sz_2_caret__lparen__minus_16_rparen_ db '2^(-16)',0
    sz_2_caret__lparen__minus_32_rparen_ db '2^(-32)',0
    sz_2_caret__lparen__minus_64_rparen_ db '2^(-64)',0
    sz_2_dot_0 db '2.0',0
    sz_2nd db '2nd',0
    sz_3 db '3',0
    sz_371_space_ms db '371 ms',0
    sz_3rd db '3rd',0
    sz_4 db '4',0
    sz_43_dot_0Hz_slash_ db '43.0Hz/',0
    sz_4th db '4th',0
    sz_5 db '5',0
    sz_5_dot_38_space_Hz_slash_ db '5.38 Hz/',0
    sz_5_dot_51_space_kHz db '5.51 kHz',0
    sz_5_dot_80_space_ms db '5.80 ms',0
    sz_5_dot_80_space_ms_slash_ db '5.80 ms/',0
    sz_5_dot_94_space_sec db '5.94 sec',0
    sz_5th db '5th',0
    sz_6 db '6',0
    sz_6th db '6th',0
    sz_7 db '7',0
    sz_7th db '7th',0
    sz_8 db '8',0
    sz_8_dot_0 db '8.0',0
    sz_9 db '9',0
    sz_92_dot_9_space_ms db '92.9 ms',0
    sz_ADSR_space_Envelope db 'ADSR Envelope',0
    sz_Add db 'Add',0
    sz_Align_space_Selection db 'Align Selection',0
    sz_Align_space_or_space_Rotate db 'Align or Rotate',0
    sz_Alpha db 'Alpha',0
    sz_Always_space__amp_Interpolate db 'Always &Interpolate',0
    sz_Analog_space_Box db 'Analog Box',0
    sz_Analog_space_Waveforms db 'Analog Waveforms',0
    sz_Auto_space_Gain_space__amp__equal_ db 'Auto Gain &=',0
    sz_Average db 'Average',0
    sz_B_amp_R2_space_band_space_reject_space_2 db 'B&R2 band reject 2',0
    sz_Bad_space_Data db 'Bad Data',0
    sz_Beginning_space_phase db 'Beginning phase',0
    sz_Buffers db 'Buffers',0
    sz_Busses db 'Busses',0
    sz_Button db 'Button',0
    sz_Changing db 'Changing',0
    sz_Check db 'Check',0
    sz_Clock_space_Cycles db 'Clock Cycles',0
    sz_Closed_space_Group db 'Closed Group',0
    sz_Color_space_Settings db 'Color Settings',0
    sz_Complex db 'Complex',0
    sz_Complex_space_Conjugate db 'Complex Conjugate',0
    sz_Connections db 'Connections',0
    sz_Controls db 'Controls',0
    sz_Create_space_Closed db 'Create Closed',0
    sz_Cross_amp_fade_space__lparen_1_slash_2_space__at__space_center_rparen_ db 'Cross&fade (1/2 @ center)',0
    sz_D_amp_erivative db 'D&erivative',0
    sz_D_space_to_space_F db 'D to F',0
    sz_D_space_to_space_M db 'D to M',0
    sz_Damper db 'Damper',0
    sz_Data_space_File db 'Data File',0
    sz_Delay db 'Delay',0
    sz_Delta_space__slash__space_Derivative db 'Delta / Derivative',0
    sz_Demultiplexer db 'Demultiplexer',0
    sz_Detail_space__lparen_enter_rparen_ db 'Detail (enter)',0
    sz_Differential_space_System db 'Differential System',0
    sz_Digital db 'Digital',0
    sz_Digital_space_Divider db 'Digital Divider',0
    sz_Direct db 'Direct',0
    sz_Display db 'Display',0
    sz_Divide db 'Divide',0
    sz_EQ db 'EQ',0
    sz_Equal_space_Space db 'Equal Space',0
    sz_Equation_space_Builder db 'Equation Builder',0
    sz_Extract_lbracket_n_rbracket_ db 'Extract[n]',0
    sz_FFT_space_Operations db 'FFT Operations',0
    sz_F_slash_P_space_Input db 'F/P Input',0
    sz_F_space_Cull db 'F Cull',0
    sz_F_space_Scale db 'F Scale',0
    sz_F_space_Shift db 'F Shift',0
    sz_F_space_to_space_D db 'F to D',0
    sz_F_space_to_space_M db 'F to M',0
    sz_Fast_space_Fourier_space_Transform db 'Fast Fourier Transform',0
    sz_File db 'File',0
    sz_Freq db 'Freq',0
    sz_GT db 'GT',0
    sz_GTE db 'GTE',0
    sz_Group db 'Group',0
    sz_Group_space_Name db 'Group Name',0
    sz_H db 'H',0
    sz_HP1_space_h_amp_igh_space_pass_space_1 db 'HP1 h&igh pass 1',0
    sz_Height db 'Height',0
    sz_Human_space_Interface_space_Device db 'Human Interface Device',0
    sz_Hz_slash_pixel db 'Hz/pixel',0
    sz_ID db 'ID',0
    sz_IIR_space_Filter db 'IIR Filter',0
    sz_IIR_space_z_minus_Plane db 'IIR z-Plane',0
    sz_Inject db 'Inject',0
    sz_Insert_lbracket_n_rbracket_ db 'Insert[n]',0
    sz_Keep_space_in_space__amp_Group db 'Keep in &Group',0
    sz_Knob db 'Knob',0
    sz_LP1_space_l_amp_ow_space_pass_space_1 db 'LP1 l&ow pass 1',0
    sz_LT db 'LT',0
    sz_LTE db 'LTE',0
    sz_Label db 'Label',0
    sz_Labels db 'Labels',0
    sz_Layout db 'Layout',0
    sz_Linear db 'Linear',0
    sz_Long_space_Name db 'Long Name',0
    sz_M_space_to_space_D db 'M to D',0
    sz_M_space_to_space_F db 'M to F',0
    sz_Math db 'Math',0
    sz_Maximum_space_Latency db 'Maximum Latency',0
    sz_Media_space_Reader db 'Media Reader',0
    sz_Mem_space_Buffer db 'Mem Buffer',0
    sz_Midi_space_In db 'Midi In',0
    sz_Midi_space_Out db 'Midi Out',0
    sz_Mixer db 'Mixer',0
    sz_Mode db 'Mode',0
    sz_Mode_colon_ db 'Mode:',0
    sz_Mult db 'Mult',0
    sz_Multiplexer db 'Multiplexer',0
    sz_Multiply db 'Multiply',0
    sz_NE db 'NE',0
    sz_Names db 'Names',0
    sz_None db 'None',0
    sz_Not_space_Assigned db 'Not Assigned',0
    sz_Num_space_Points_colon_ db 'Num Points:',0
    sz_ON db 'ON',0
    sz_O_minus_Scope db 'O-Scope',0
    sz_Oscillator db 'Oscillator',0
    sz_P_amp_an_space__lparen_1_slash_2_space__at__space_center_rparen_ db 'P&an (1/2 @ center)',0
    sz_Pin_space_Interface db 'Pin Interface',0
    sz_Pins db 'Pins',0
    sz_Pitch_space_Quantizer db 'Pitch Quantizer',0
    sz_Points db 'Points',0
    sz_Power db 'Power',0
    sz_Power_space_Spectrum db 'Power Spectrum',0
    sz_Preset db 'Preset',0
    sz_Presets db 'Presets',0
    sz_Probe db 'Probe',0
    sz_Pull db 'Pull',0
    sz_RC_space__amp_above db 'RC &above',0
    sz_RC_space_b_amp_elow db 'RC b&elow',0
    sz_RC_space_bo_amp_th db 'RC bo&th',0
    sz_Random_slash_Noise db 'Random/Noise',0
    sz_Range db 'Range',0
    sz_Rate db 'Rate',0
    sz_Readout db 'Readout',0
    sz_Replace db 'Replace',0
    sz_Runge_minus_Kutta db 'Runge-Kutta',0
    sz_S db 'S',0
    sz_SAT db 'SAT',0
    sz_Sample_space_and_space_Hold db 'Sample and Hold',0
    sz_Scale db 'Scale',0
    sz_Scope db 'Scope',0
    sz_Scroll db 'Scroll',0
    sz_Shift_space__amp_Frame_space_and_space_Hold db 'Shift &Frame and Hold',0
    sz_Short_space_Name db 'Short Name',0
    sz_Sign db 'Sign',0
    sz_Slider db 'Slider',0
    sz_Small db 'Small',0
    sz_Small_space__lparen_Enter_rparen_ db 'Small (Enter)',0
    sz_Sonograph db 'Sonograph',0
    sz_Sort_space_By_space_Amplitude db 'Sort By Amplitude',0
    sz_Spectrum db 'Spectrum',0
    sz_Sweep db 'Sweep',0
    sz_Taper_colon_ db 'Taper:',0
    sz_Text_space_Reader db 'Text Reader',0
    sz_Text_space_Writer db 'Text Writer',0
    sz_Transform db 'Transform',0
    sz_Trig db 'Trig',0
    sz_Trigger db 'Trigger',0
    sz_Turns_colon_ db 'Turns:',0
    sz_Unconnect db 'Unconnect',0
    sz_Units_colon_ db 'Units:',0
    sz_V db 'V',0
    sz_VST_space_Plugin db 'VST Plugin',0
    sz_VU_space_Meter_space__amp_1 db 'VU Meter &1',0
    sz_VU_space_Meter_space__amp_2 db 'VU Meter &2',0
    sz_View_space_or_space_Edit_space_Contents_space__lparen_Enter_rparen_ db 'View or Edit Contents (Enter)',0
    sz_Wave_space_In db 'Wave In',0
    sz_Wave_space_Out db 'Wave Out',0
    sz_Wave_space_Writer db 'Wave Writer',0
    sz_X_minus_Y db 'X-Y',0
    sz__amp_0 db '&0',0
    sz__amp_0_space_to_space__plus_1 db '&0 to +1',0
    sz__amp_3 db '&3',0
    sz__amp_5 db '&5',0
    sz__amp_7 db '&7',0
    sz__amp_9 db '&9',0
    sz__amp_Absolute db '&Absolute',0
    sz__amp_Audio db '&Audio',0
    sz__amp_BP2_space_band_space_pass_space_2 db '&BP2 band pass 2',0
    sz__amp_Band_space_Pass db '&Band Pass',0
    sz__amp_Crossfade_space__lparen_1_space__at__space_center_rparen_ db '&Crossfade (1 @ center)',0
    sz__amp_Demultiplex_space__lparen_0_space__at__space_center_rparen_ db '&Demultiplex (0 @ center)',0
    sz__amp_Detailed db '&Detailed',0
    sz__amp_Digital db '&Digital',0
    sz__amp_Forward db '&Forward',0
    sz__amp_Frequency db '&Frequency',0
    sz__amp_HP2_space_high_space_pass_space_2 db '&HP2 high pass 2',0
    sz__amp_High_space_Pass db '&High Pass',0
    sz__amp_Horz db '&Horz',0
    sz__amp_LP2_space_low_space_pass_space_2 db '&LP2 low pass 2',0
    sz__amp_Less db '&Less',0
    sz__amp_Linear db '&Linear',0
    sz__amp_Low_space_Pass db '&Low Pass',0
    sz__amp_Midi_space_note db '&Midi note',0
    sz__amp_More db '&More',0
    sz__amp_Multiplex_space__lparen_0_space__at__space_center_rparen_ db '&Multiplex (0 @ center)',0
    sz__amp_Normal db '&Normal',0
    sz__amp_Pan_space__lparen_1_space__at__space_center_rparen_ db '&Pan (1 @ center)',0
    sz__amp_Phase db '&Phase',0
    sz__amp_Reverse db '&Reverse',0
    sz__amp_Sample_space_and_space_Hold db '&Sample and Hold',0
    sz__amp_Small db '&Small',0
    sz__amp_Status db '&Status',0
    sz__amp_U db '&U',0
    sz__amp_V db '&V',0
    sz__amp_Value db '&Value',0
    sz__amp_Vert db '&Vert',0
    sz__amp_W db '&W',0
    sz__amp_Window db '&Window',0
    sz__amp_Wrap db '&Wrap',0
    sz__amp_X db '&X',0
    sz__amp_Y db '&Y',0
    sz__amp_Z db '&Z',0
    sz__amp_Zero_space_start db '&Zero start',0
    sz__amp__at_ db '&@',0
    sz__amp__equal__plus_1_space_to_space__minus_1 db '&=+1 to -1',0
    sz__amp__minus_1_space_to_space__plus_1 db '&-1 to +1',0
    sz__amp__percent_ db '&%',0
    sz__amp__pound_ db '&#',0
    sz__amp_a db '&a',0
    sz__amp_and db '&and',0
    sz__amp_auto_space_retrigger db '&auto retrigger',0
    sz__amp_b db '&b',0
    sz__amp_cos_lparen__space__rparen_ db '&cos( )',0
    sz__amp_ignore_space_T db '&ignore T',0
    sz__amp_int_lparen__space__rparen_ db '&int( )',0
    sz__amp_ln2 db '&ln2',0
    sz__amp_mag_lparen__space__rparen_ db '&mag( )',0
    sz__amp_momentary db '&momentary',0
    sz__amp_nand db '&nand',0
    sz__amp_neg_lparen__space__rparen_ db '&neg( )',0
    sz__amp_or db '&or',0
    sz__amp_pi db '&pi',0
    sz__amp_push_space_on_slash_off db '&push on/off',0
    sz__amp_ramp_space_1 db '&ramp 1',0
    sz__amp_set_space__slash__space_reset db '&set / reset',0
    sz__amp_sin_lparen__space__rparen_ db '&sin( )',0
    sz__amp_sine db '&sine',0
    sz__amp_tanh_lparen__space__rparen_ db '&tanh( )',0
    sz__amp_triangle db '&triangle',0
    sz__amp_xor db '&xor',0
    sz__dot_ db '.',0
    sz__equal_ db '=',0
    sz__langle__minus_ db '<-',0
    sz__lparen__space__rparen_ db '( )',0
    sz__minus_ db '-',0
    sz__minus__amp_180 db '-&180',0
    sz__minus__rangle_ db '->',0
    sz__percent_ db '%',0
    sz__plus_ db '+',0
    sz__plus_1_dot_0 db '+1.0',0
    sz__plus__equal_ db '+=',0
    sz__plus__slash__minus__space_1 db '+/- 1',0
    sz__pound_5th db '#5th',0
    sz__slash_ db '/',0
    sz__space_Category db ' Category',0
    sz__space_Members db ' Members',0
    sz__space_equation_space__lparen_push_space_to_space_edit_rparen_ db ' equation (push to edit)',0
    sz__star_ db '*',0
    sz__star__equal_ db '*=',0
    sz_add db 'add',0
    sz_b2nd db 'b2nd',0
    sz_b3rd db 'b3rd',0
    sz_b5th db 'b5th',0
    sz_b7th db 'b7th',0
    sz_bak db 'bak',0
    sz_chan db 'chan',0
    sz_clock_space_start_space_stop db 'clock start stop',0
    sz_controllers db 'controllers',0
    sz_ctrl db 'ctrl',0
    sz_ctrl_space_N db 'ctrl N',0
    sz_default db 'default',0
    sz_del db 'del',0
    sz_derivative db 'derivative',0
    sz_device db 'device',0
    sz_dn db 'dn',0
    sz_du db 'du',0
    sz_du_space__equal_ db 'du =',0
    sz_dv db 'dv',0
    sz_dv_space__equal_ db 'dv =',0
    sz_dw db 'dw',0
    sz_dw_space__equal_ db 'dw =',0
    sz_dx db 'dx',0
    sz_dx_space__equal_ db 'dx =',0
    sz_dy db 'dy',0
    sz_dy_space__equal_ db 'dy =',0
    sz_dz db 'dz',0
    sz_dz_space__equal_ db 'dz =',0
    sz_grid db 'grid',0
    sz_imag db 'imag',0
    sz_input_space_mode db 'input mode',0
    sz_ins db 'ins',0
    sz_integration db 'integration',0
    sz_l2_amp_e db 'l2&e',0
    sz_l_amp_og2_lparen__space__rparen_ db 'l&og2( )',0
    sz_length db 'length',0
    sz_li_amp_near db 'li&near',0
    sz_lo_amp_grithmic db 'lo&grithmic',0
    sz_loop db 'loop',0
    sz_low_space_latency db 'low latency',0
    sz_m db 'm',0
    sz_make_space_tracker db 'make tracker',0
    sz_mode db 'mode',0
    sz_multiply db 'multiply',0
    sz_n db 'n',0
    sz_name db 'name',0
    sz_neg db 'neg',0
    sz_no_amp_r db 'no&r',0
    sz_no_space__amp_retrigger db 'no &retrigger',0
    sz_no_space__amp_sustain db 'no &sustain',0
    sz_note db 'note',0
    sz_number db 'number',0
    sz_off db 'off',0
    sz_on db 'on',0
    sz_output db 'output',0
    sz_output_space__lparen_12_space_max_rparen_ db 'output (12 max)',0
    sz_output_space_filter db 'output filter',0
    sz_patch db 'patch',0
    sz_patch_space_N db 'patch N',0
    sz_pitch_space_wheel db 'pitch wheel',0
    sz_port db 'port',0
    sz_pos db 'pos',0
    sz_press db 'press',0
    sz_pressure db 'pressure',0
    sz_r db 'r',0
    sz_r_amp_amp_space_2 db 'r&amp 2',0
    sz_ra_amp_mp db 'ra&mp',0
    sz_real db 'real',0
    sz_redo db 'redo',0
    sz_reset db 'reset',0
    sz_s db 's',0
    sz_s_amp_qrt_lparen__space__rparen_ db 's&qrt( )',0
    sz_s_amp_quare_space_1 db 's&quare 1',0
    sz_s_space_input db 's input',0
    sz_saturation db 'saturation',0
    sz_seek_space_sync db 'seek sync',0
    sz_set db 'set',0
    sz_si_amp_gn_lparen__space__rparen_ db 'si&gn( )',0
    sz_small_space__equal_ db 'small =',0
    sz_sq_amp_uare_space_2 db 'sq&uare 2',0
    sz_squar_amp_e db 'squar&e',0
    sz_status db 'status',0
    sz_step_space_input db 'step input',0
    sz_stream db 'stream',0
    sz_subtract db 'subtract',0
    sz_t db 't',0
    sz_tX db 'tX',0
    sz_tX1 db 'tX1',0
    sz_tX2 db 'tX2',0
    sz_tX3 db 'tX3',0
    sz_t_space_Start db 't Start',0
    sz_t_space_input db 't input',0
    sz_track_space_N db 'track N',0
    sz_track_space_t db 'track t',0
    sz_tracker db 'tracker',0
    sz_u db 'u',0
    sz_u1 db 'u1',0
    sz_u2 db 'u2',0
    sz_u3 db 'u3',0
    sz_u4 db 'u4',0
    sz_undo db 'undo',0
    sz_up db 'up',0
    sz_v db 'v',0
    sz_v1 db 'v1',0
    sz_v2 db 'v2',0
    sz_v3 db 'v3',0
    sz_v4 db 'v4',0
    sz_w db 'w',0
    sz_w1 db 'w1',0
    sz_w2 db 'w2',0
    sz_w3 db 'w3',0
    sz_w4 db 'w4',0
    sz_wheel db 'wheel',0
    sz_x db 'x',0
    sz_x1 db 'x1',0
    sz_x2 db 'x2',0
    sz_x3 db 'x3',0
    sz_x4 db 'x4',0
    sz_y db 'y',0
    sz_y1 db 'y1',0
    sz_y2 db 'y2',0
    sz_y3 db 'y3',0
    sz_y4 db 'y4',0
    sz_z db 'z',0
    sz_z1 db 'z1',0
    sz_z2 db 'z2',0
    sz_z3 db 'z3',0
    sz_z4 db 'z4',0


END
